"""empty message

Revision ID: 277cf303711a
Revises: 
Create Date: 2020-02-12 17:40:53.639088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '277cf303711a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('addtime', sa.Integer(), nullable=True),
    sa.Column('update_time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_role_addtime'), 'role', ['addtime'], unique=False)
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('addtime', sa.Integer(), nullable=True),
    sa.Column('update_time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_tag_addtime'), 'tag', ['addtime'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=11), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('sex', sa.String(length=1), nullable=False),
    sa.Column('face', sa.String(length=255), nullable=True),
    sa.Column('info', sa.Text(), nullable=True),
    sa.Column('addtime', sa.Integer(), nullable=True),
    sa.Column('update_time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('password'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_user_addtime'), 'user', ['addtime'], unique=False)
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=11), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('sex', sa.SmallInteger(), nullable=True),
    sa.Column('face', sa.String(length=255), nullable=True),
    sa.Column('info', sa.String(length=300), nullable=True),
    sa.Column('addtime', sa.Integer(), nullable=True),
    sa.Column('update_time', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('password'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_admin_addtime'), 'admin', ['addtime'], unique=False)
    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('brief', sa.Text(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('release_time', sa.Date(), nullable=True),
    sa.Column('score', sa.SmallInteger(), nullable=True),
    sa.Column('playnum', sa.BigInteger(), nullable=True),
    sa.Column('commentnum', sa.BigInteger(), nullable=True),
    sa.Column('addtime', sa.Integer(), nullable=True),
    sa.Column('update_time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movie_addtime'), 'movie', ['addtime'], unique=False)
    op.create_table('user_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('last_login_time', sa.DateTime(), nullable=True),
    sa.Column('addtime', sa.Integer(), nullable=True),
    sa.Column('last_ip', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_log_addtime'), 'user_log', ['addtime'], unique=False)
    op.create_index(op.f('ix_user_log_last_login_time'), 'user_log', ['last_login_time'], unique=False)
    op.create_table('admin_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=100), nullable=True),
    sa.Column('last_login_time', sa.DateTime(), nullable=True),
    sa.Column('last_ip', sa.String(length=50), nullable=True),
    sa.Column('addtime', sa.Integer(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_log_addtime'), 'admin_log', ['addtime'], unique=False)
    op.create_index(op.f('ix_admin_log_last_login_time'), 'admin_log', ['last_login_time'], unique=False)
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('addtime', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_addtime'), 'comment', ['addtime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comment_addtime'), table_name='comment')
    op.drop_table('comment')
    op.drop_index(op.f('ix_admin_log_last_login_time'), table_name='admin_log')
    op.drop_index(op.f('ix_admin_log_addtime'), table_name='admin_log')
    op.drop_table('admin_log')
    op.drop_index(op.f('ix_user_log_last_login_time'), table_name='user_log')
    op.drop_index(op.f('ix_user_log_addtime'), table_name='user_log')
    op.drop_table('user_log')
    op.drop_index(op.f('ix_movie_addtime'), table_name='movie')
    op.drop_table('movie')
    op.drop_index(op.f('ix_admin_addtime'), table_name='admin')
    op.drop_table('admin')
    op.drop_index(op.f('ix_user_addtime'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_tag_addtime'), table_name='tag')
    op.drop_table('tag')
    op.drop_index(op.f('ix_role_addtime'), table_name='role')
    op.drop_table('role')
    # ### end Alembic commands ###
