"""empty message

Revision ID: 3052508d288a
Revises: 277cf303711a
Create Date: 2020-03-05 16:05:02.551076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3052508d288a'
down_revision = '277cf303711a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secret_protection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=50), nullable=False),
    sa.Column('answer', sa.String(length=10), nullable=False),
    sa.Column('addtime', sa.Integer(), nullable=True),
    sa.Column('update_time', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_secret_protection_addtime'), 'secret_protection', ['addtime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_secret_protection_addtime'), table_name='secret_protection')
    op.drop_table('secret_protection')
    # ### end Alembic commands ###
