"""empty message

Revision ID: b4f6d3caffbd
Revises: ea93ec008447
Create Date: 2020-03-08 14:08:45.004274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4f6d3caffbd'
down_revision = 'ea93ec008447'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'url')
    # ### end Alembic commands ###
