"""empty message

Revision ID: e1c84fb4e17a
Revises: b4f6d3caffbd
Create Date: 2020-03-08 16:37:23.878757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1c84fb4e17a'
down_revision = 'b4f6d3caffbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('content', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'content')
    # ### end Alembic commands ###
