"""empty message

Revision ID: ea93ec008447
Revises: 3052508d288a
Create Date: 2020-03-05 16:11:18.537383

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ea93ec008447'
down_revision = '3052508d288a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'info')
    op.drop_column('admin', 'face')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('face', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True))
    op.add_column('admin', sa.Column('info', mysql.VARCHAR(collation='utf8mb4_general_ci', length=300), nullable=True))
    # ### end Alembic commands ###
